/**
 * @smart-edms/i18n — English baseline: `ai.common` namespace (spec §16.4)
 *
 * Common AI assistant UI chrome: status, modes, model selection.
 */

const aiCommon = {
  'title': 'AI assistant',
  'subtitle': 'Your AI helper inside Smart EDMS.',
  'status.online': 'AI assistant online',
  'status.offline': 'AI assistant offline',
  'status.thinking': 'AI is thinking…',
  'status.processing': 'Processing…',
  'status.unavailable': 'AI assistant is temporarily unavailable.',
  'status.degraded': 'AI assistant is in degraded mode.',
  'status.rateLimited': 'AI assistant rate limit reached. Please try again in a moment.',

  'mode.title': 'AI mode',
  'mode.external': 'External AI',
  'mode.local': 'Local AI',
  'mode.hybrid': 'Hybrid',
  'mode.description.external': 'AI requests are sent to an external provider. Faster, but data leaves your tenant.',
  'mode.description.local': 'AI requests run on a local model. Slower, but data never leaves your tenant.',
  'mode.description.hybrid': 'Smart EDMS picks the right model for each request based on sensitivity and speed.',

  'model.title': 'Model',
  'model.select': 'Select model',
  'model.current': 'Current model: {{model}}',
  'model.capabilities': 'Capabilities',
  'model.contextWindow': 'Context window',
  'model.maxTokens': 'Max tokens per request',
  'model.updated': 'Model updated to {{model}}.',

  'session.title': 'AI session',
  'session.new': 'New session',
  'session.history': 'Session history',
  'session.clear': 'Clear session',
  'session.clear.confirm': 'Clear this AI session? The conversation will be permanently deleted.',
  'session.export': 'Export session',
  'session.empty': 'No AI sessions yet.',
  'session.count': '{count, plural, one {# session} other {# sessions}}',

  'message.placeholder': 'Ask the AI assistant anything about your documents…',
  'message.send': 'Send',
  'message.stop': 'Stop',
  'message.regenerate': 'Regenerate response',
  'message.copy': 'Copy response',
  'message.copy.success': 'Response copied to clipboard.',
  'message.edit': 'Edit message',
  'message.delete': 'Delete message',
  'message.delete.confirm': 'Delete this message?',
  'message.role.user': 'You',
  'message.role.assistant': 'AI assistant',
  'message.role.system': 'System',
  'message.timestamp': 'Sent at {{time}}',

  'settings.title': 'AI assistant settings',
  'settings.subtitle': 'Configure how the AI behaves for you.',
  'settings.mode': 'Default mode',
  'settings.model': 'Default model',
  'settings.citations': 'Always show citations',
  'settings.disclaimer': 'Show disclaimer on every response',
  'settings.confirmationRequired': 'Require confirmation for all actions',
  'settings.proactive': 'Allow proactive suggestions',
  'settings.maxTokensPerRequest': 'Max tokens per request',
  'settings.maxTokensPerDay': 'Max tokens per day',
  'settings.usedToday': 'Used today: {{used}} of {{limit}} tokens',
  'settings.usage.unlimited': 'Usage: unlimited',
  'settings.save': 'Save settings',
  'settings.saved': 'AI settings updated.',

  'tools.title': 'Available tools',
  'tools.subtitle': 'The AI can use these tools. Your administrator controls which are enabled.',
  'tools.enabled': 'Enabled',
  'tools.disabled': 'Disabled',
  'tools.allowlist': 'Tool allowlist',
  'tools.disclaimer': 'Tools are audited. Every invocation is recorded in the audit log.',

  'disclaimer.short': 'AI-generated. Verify before relying on it.',
  'disclaimer.long': 'This response was generated by an AI assistant. It may contain errors. Verify important details against the cited sources before relying on this response.',

  'feedback.title': 'Was this response helpful?',
  'feedback.helpful': 'Helpful',
  'feedback.notHelpful': 'Not helpful',
  'feedback.flag': 'Report a problem',
  'feedback.flag.placeholder': 'What went wrong?',
  'feedback.thanks': 'Thanks for the feedback!',

  'history.title': 'Conversation history',
  'history.empty': 'No messages yet. Ask the AI something!',
  'history.scrollBottom': 'Jump to latest',
  'history.scrollTop': 'Jump to start',

  'quota.title': 'AI quota',
  'quota.subtitle': 'Your AI usage for today.',
  'quota.tokensUsed': 'Tokens used',
  'quota.requestsMade': 'Requests made',
  'quota.resets': 'Resets in {{hours}} hours',
  'quota.exceeded': 'You have reached your daily AI quota. Please try again tomorrow.',
  'quota.warning': 'You have used {{percent}}% of your daily AI quota.',
} as const;

export default aiCommon;
