/**
 * @smart-edms/types — provenance, C2PA, evidence (spec §9.12)
 *
 * Purpose: model provenance manifests, C2PA Content Credentials, evidence
 * packages, chain-of-custody entries, and forgery-detection results.
 *
 * Critical rules (spec §9.12):
 *  - Audit storage is append-only; hash chaining or equivalent tamper-
 *    evidence is mandatory.
 *  - C2PA manifests are verified on ingest where enabled.
 *  - The Deepfake and Forgery Detection Pipeline flags AI-generated PDFs,
 *    manipulated images, and spoofed digital signatures.
 *  - Chain-of-custody anchoring is enabled for critical documents.
 */

import type { HashHex, ISODateString, UUID } from './common';
import type { TenantId } from './tenant';
import type { UserId } from './user';
import type { DocumentId, DocumentVersionId } from './document';

/** Branded provenance-manifest identifier. */
export type ProvenanceManifestId = UUID & { readonly __provenance: 'ProvenanceManifestId' };

/** Branded evidence-package identifier. */
export type EvidencePackageId = UUID & { readonly __evidence: 'EvidencePackageId' };

/** Branded chain-of-custody entry identifier. */
export type ChainOfCustodyEntryId = UUID & { readonly __custody: 'ChainOfCustodyEntryId' };

/** Branded C2PA manifest identifier. */
export type C2PAManifestId = UUID & { readonly __c2pa: 'C2PAManifestId' };

/** Kind of action recorded in a chain-of-custody entry. */
export type CustodyAction =
  | 'ingest'
  | 'transfer'
  | 'transform'
  | 'redact'
  | 'export'
  | 'verify'
  | 'accession'
  | 'release';

/**
 * Chain-of-custody entry (spec §9.12). Anchors a critical document's
 * lifecycle in a tamper-evident ledger. Each entry references the previous
 * entry's hash to form a chain.
 */
export interface ChainOfCustodyEntry {
  readonly id: ChainOfCustodyEntryId;
  readonly tenantId: TenantId;
  readonly documentId: DocumentId;
  readonly versionId: DocumentVersionId | null;
  readonly action: CustodyAction;
  readonly actorUserId: UserId | null;
  readonly actorLabel: string;
  /** Hash of the previous entry in the chain; null for the genesis entry. */
  readonly previousHash: HashHex | null;
  /** Hash of this entry's canonical payload. */
  readonly entryHash: HashHex;
  readonly reasonKey: string | null;
  readonly occurredAt: ISODateString;
  /** Optional signature over the canonical entry payload. */
  readonly signature: {
    readonly algorithm: string;
    readonly keyId: string;
    readonly value: string;
  } | null;
}

/**
 * C2PA Content Credentials manifest (spec §9.12). Verified on ingest where
 * enabled. The `manifestJson` is the canonical C2PA manifest blob.
 */
export interface C2PAManifest {
  readonly id: C2PAManifestId;
  readonly tenantId: TenantId;
  readonly documentId: DocumentId;
  readonly versionId: DocumentVersionId;
  /** Canonical C2PA manifest JSON. */
  readonly manifestJson: string;
  /** Hash of the manifest, for tamper detection. */
  readonly manifestHash: HashHex;
  /** Whether signature verification succeeded. */
  readonly signatureVerified: boolean;
  /** Whether the manifest was generated by Smart EDMS itself. */
  readonly selfIssued: boolean;
  /** Tool / generator that produced the manifest, per C2PA. */
  readonly generator: string | null;
  readonly verifiedAt: ISODateString;
}

/**
 * Forgery detection verdict (spec §9.12). Produced by the deepfake and
 * forgery detection pipeline.
 */
export type ForgeryVerdict =
  | 'clean'
  | 'suspicious'
  | 'likely_forged'
  | 'ai_generated'
  | 'manipulated'
  | 'spoofed_signature';

/**
 * Forgery detection result (spec §9.12). Pixel-level anomalies, metadata
 * stripping, and signature biometrics are analysed.
 */
export interface ForgeryDetectionResult {
  readonly id: UUID;
  readonly tenantId: TenantId;
  readonly documentId: DocumentId;
  readonly versionId: DocumentVersionId;
  readonly verdict: ForgeryVerdict;
  /** Confidence score in [1,100]. */
  readonly confidence: number;
  /** Localised explanation key shown to reviewers. */
  readonly explanationKey: string;
  /** Per-signal findings, for transparency. */
  readonly signals: ReadonlyArray<{
    readonly code: string;
    readonly triggered: boolean;
    readonly severity: 'info' | 'warning' | 'critical';
    readonly detailKey: string | null;
  }>;
  readonly computedAt: ISODateString;
  /** Whether the document was routed to a human reviewer. */
  readonly routedToReview: boolean;
}

/**
 * Provenance manifest (spec §9.12). Aggregates the chain of custody, C2PA
 * manifest, and forgery-detection results for a document version into a
 * single immutable envelope.
 */
export interface ProvenanceManifest {
  readonly id: ProvenanceManifestId;
  readonly tenantId: TenantId;
  readonly documentId: DocumentId;
  readonly versionId: DocumentVersionId;
  readonly custody: readonly ChainOfCustodyEntry[];
  readonly c2pa: C2PAManifest | null;
  readonly forgery: ForgeryDetectionResult | null;
  /** Aggregate root hash over the manifest, for tamper detection. */
  readonly rootHash: HashHex;
  readonly generatedAt: ISODateString;
}

/**
 * Evidence package (spec §9.12). Exportable for compliance review;
 * contains the provenance manifest plus selected audit events and
 * document versions. Generated asynchronously for large datasets.
 */
export interface EvidencePackage {
  readonly id: EvidencePackageId;
  readonly tenantId: TenantId;
  readonly documentId: DocumentId;
  /** Versions included in the package. */
  readonly versionIds: readonly DocumentVersionId[];
  /** Provenance manifest snapshot. */
  readonly provenance: ProvenanceManifest;
  /** Audit events included in the package. */
  readonly auditEventIds: readonly UUID[];
  /** Localised package title key. */
  readonly titleKey: string;
  /** Hash of the packaged archive, for tamper detection. */
  readonly packageHash: HashHex;
  /** Status of the asynchronous generation job. */
  readonly status: 'pending' | 'generating' | 'ready' | 'failed' | 'expired';
  readonly requestedBy: UserId;
  readonly requestedAt: ISODateString;
  readonly readyAt: ISODateString | null;
  /** Object-storage opaque key for the generated archive. */
  readonly storageKey: string | null;
  /** Signature over the canonical package manifest. */
  readonly signature: {
    readonly algorithm: string;
    readonly keyId: string;
    readonly value: string;
  } | null;
}
