/**
 * @smart-edms/license-core — MIME type constants (spec §4.3)
 *
 * Purpose: canonical MIME types for the three Smart EDMS license file
 * formats. Used by HTTP transports (Content-Type / Accept headers), by
 * the Electron desktop app's file-picker filters, and by the on-premise
 * backend's import/export endpoints.
 *
 * These MIME types are intentionally `application/x-*` (vendor tree)
 * because the formats are Smart-EDMS-specific and have no IANA-registered
 * media type.
 */

/**
 * MIME type for the signed license artifact (`.sedmslic`).
 *
 * Format: canonical JSON envelope `{ v, type: 'sedms.license', alg, kid,
 * payload, sig }` per spec §4.3 / §12.5.
 */
export const SEDMSLIC_MIME = 'application/x-sedms-license';

/**
 * MIME type for the offline activation request (`.sedmsreq`).
 *
 * Format: canonical JSON per spec §12.6. Generated by the on-premise
 * backend; shipped out-of-band (e.g. USB token, email attachment) to
 * the licensing server for offline activation.
 */
export const SEDMSREQ_MIME = 'application/x-sedms-request';

/**
 * MIME type for the signed certificate revocation list (`.sedmscrl`).
 *
 * Format: canonical JSON per spec §4.3 / §12.4. Fetched by the on-premise
 * backend when online and consulted during every license signature
 * verification.
 */
export const SEDMSCRL_MIME = 'application/x-sedms-crl';

/**
 * File extensions mapped to their MIME types. Used by file pickers and
 * by content-type negotiation on the import/export endpoints.
 */
export const SEDMS_EXTENSIONS: Readonly<Record<string, string>> = Object.freeze({
  '.sedmslic': SEDMSLIC_MIME,
  '.sedmsreq': SEDMSREQ_MIME,
  '.sedmscrl': SEDMSCRL_MIME,
});

/**
 * Reverse map: MIME type → primary file extension (without leading dot).
 */
export const SEDMS_MIME_EXT: Readonly<Record<string, string>> = Object.freeze({
  [SEDMSLIC_MIME]: 'sedmslic',
  [SEDMSREQ_MIME]: 'sedmsreq',
  [SEDMSCRL_MIME]: 'sedmscrl',
});
