"use strict";
/**
 * @smart-edms/license-core — `.sedmsreq` offline activation request (spec §12.6)
 *
 * Purpose: build and parse the offline activation request file. This
 * file is generated by an air-gapped on-premise backend and shipped
 * out-of-band (USB token, secure email, paper printout + manual retyping)
 * to the licensing server, which then issues a signed `.sedmslic` in
 * return.
 *
 * Format (spec §12.6):
 *   {
 *     "v": 1,
 *     "type": "sedms.request",
 *     "requestId": "<uuid>",
 *     "productId": "<uuid>",
 *     "deploymentId": "<uuid>",
 *     "appVersion": "1.0.0",
 *     "generatedAt": "<iso-8601>",
 *     "machineFingerprint": { ...InstallationFingerprint... },
 *     "installationPublicKey": "<pem>",
 *     "os": "linux",
 *     "arch": "x64",
 *     "contactEmail": "ops@example.com" | null,
 *     "nonce": "<≥16 chars>"
 *   }
 *
 * Critical rules (spec §12.6):
 *  - The request itself is NOT signed by the licensing server's key
 *    (it's a request, not a certificate). It MAY be signed by the
 *    installation key to prove possession; that signature lives in a
 *    separate envelope field managed by the licensing server.
 *  - The `nonce` MUST be single-use; the licensing server rejects any
 *    request whose nonce has been seen before.
 *  - The serialized form is canonicalized JSON (sorted keys, no
 *    whitespace) so that the licensing server can compute a stable
 *    request hash for deduplication.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OFFLINE_REQUEST_VERSION = void 0;
exports.buildOfflineRequest = buildOfflineRequest;
exports.parseOfflineRequest = parseOfflineRequest;
const canonicalize_js_1 = require("./canonicalize.js");
/** Offline request file schema version (spec §12.6). */
exports.OFFLINE_REQUEST_VERSION = 1;
/**
 * Build the canonical `.sedmsreq` file content from the input fields.
 *
 * The output is canonicalized JSON (sorted keys, no whitespace). This
 * exact byte sequence is what gets written to disk and shipped to the
 * licensing server.
 *
 * @param input - the request fields.
 * @returns canonicalized JSON string.
 * @throws {Error} if `nonce` is shorter than 16 characters or if any
 *   field fails canonicalization.
 */
function buildOfflineRequest(input) {
    if (typeof input.nonce !== 'string' || input.nonce.length < 16) {
        throw new Error('buildOfflineRequest: nonce must be at least 16 characters');
    }
    if (typeof input.installationPublicKey !== 'string' || input.installationPublicKey.length === 0) {
        throw new Error('buildOfflineRequest: installationPublicKey is required');
    }
    const req = {
        v: exports.OFFLINE_REQUEST_VERSION,
        type: 'sedms.request',
        requestId: input.requestId,
        productId: input.productId,
        deploymentId: input.deploymentId,
        appVersion: input.appVersion,
        generatedAt: input.generatedAt,
        machineFingerprint: input.machineFingerprint,
        installationPublicKey: input.installationPublicKey,
        os: input.os,
        arch: input.arch,
        contactEmail: input.contactEmail,
        nonce: input.nonce,
    };
    return (0, canonicalize_js_1.canonicalizeJson)(req);
}
/**
 * Parse a `.sedmsreq` file content into an `OfflineRequest` object.
 *
 * Performs structural validation but NOT cryptographic validation —
 * the request itself is not signed. The licensing server is responsible
 * for additional validation (nonce uniqueness, productId existence,
 * deploymentId whitelist, etc.).
 *
 * @param content - canonical or pretty JSON string.
 * @returns the parsed `OfflineRequest`.
 * @throws {Error} if the content is malformed JSON or fails structural
 *   validation.
 */
function parseOfflineRequest(content) {
    if (typeof content !== 'string' || content.length === 0) {
        throw new Error('parseOfflineRequest: content must be a non-empty string');
    }
    let parsed;
    try {
        parsed = JSON.parse(content);
    }
    catch (e) {
        throw new Error(`parseOfflineRequest: invalid JSON: ${e instanceof Error ? e.message : String(e)}`);
    }
    if (parsed == null || typeof parsed !== 'object') {
        throw new Error('parseOfflineRequest: content is not a JSON object');
    }
    const obj = parsed;
    if (obj.v !== exports.OFFLINE_REQUEST_VERSION) {
        throw new Error(`parseOfflineRequest: unsupported version ${String(obj.v)}`);
    }
    if (obj.type !== 'sedms.request') {
        throw new Error(`parseOfflineRequest: wrong type '${String(obj.type)}'`);
    }
    const required = [
        'requestId',
        'productId',
        'deploymentId',
        'appVersion',
        'generatedAt',
        'machineFingerprint',
        'installationPublicKey',
        'os',
        'arch',
        'nonce',
    ];
    for (const key of required) {
        if (!(key in obj) || obj[key] === undefined || obj[key] === null) {
            throw new Error(`parseOfflineRequest: missing required field '${String(key)}'`);
        }
    }
    // `contactEmail` is nullable, so skip its absence check above.
    return obj;
}
//# sourceMappingURL=offline-request.js.map